"""
Section 4.2 VAR / VECM and Granger causality analysis.

This script reads the daily DE-AT-LU panel generated by the project scaffold,
fits the multivariate system used in the paper, and writes all outputs into
the sibling VAR4.2 directory.
"""
from __future__ import annotations

import math
import re
import warnings
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller, grangercausalitytests, kpss
from statsmodels.tsa.vector_ar.vecm import VECM, coint_johansen, select_coint_rank


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
DATA_DIR = ROOT / "dataset"
OUT = ROOT
CODE_DIR = SCRIPT_DIR
TABLE_DIR = ROOT / "tables"
FIG_DIR = ROOT / "figures"

RAW_COLS = {
    "load": "DE_load_actual_entsoe_transparency",
    "wind": "DE_wind_generation_actual",
    "solar": "DE_solar_generation_actual",
    "price": "DE_price_day_ahead",
}

ORDER = ["wind", "solar", "load", "price"]
LABELS = {
    "wind": "Wind generation",
    "solar": "Solar generation",
    "load": "Load",
    "price": "Day-ahead price",
}


def ensure_dirs() -> None:
    for path in [TABLE_DIR, FIG_DIR]:
        path.mkdir(parents=True, exist_ok=True)


def find_file(filename: str) -> Path:
    """优先在 ./data/ 中查找，再退回到全目录扫描。"""
    candidate = DATA_DIR / filename
    if candidate.exists():
        return candidate
    matches = [p for p in ROOT.rglob(filename)
               if "tables" not in p.parts and "figures" not in p.parts]
    if not matches:
        raise FileNotFoundError(f"Cannot find {filename} under {ROOT}")
    return sorted(matches, key=lambda p: len(p.parts))[0]


def find_template() -> Path | None:
    """新平铺结构下没有论文模板，返回 None。"""
    return None


def load_daily_panel() -> pd.DataFrame:
    data_path = find_file("de_panel_daily.csv")
    df = pd.read_csv(data_path, parse_dates=["ts"]).set_index("ts")
    out = df[list(RAW_COLS.values())].rename(columns={v: k for k, v in RAW_COLS.items()})
    out = out.dropna().sort_index()
    out.to_csv(TABLE_DIR / "table_var_input_daily.csv", encoding="utf-8-sig")
    return out


def transform_data(raw: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, float]:
    """Return transformed levels and first differences.

    Wind, solar and load are positive physical quantities, so log(x + 1) is
    used. Electricity prices include a few negative daily averages; for price
    we apply a constant shift before logging to preserve all observations and
    keep the transformation monotone.
    """
    shift = max(0.0, 1.0 - float(raw["price"].min()))
    levels = pd.DataFrame(index=raw.index)
    levels["wind"] = np.log(raw["wind"] + 1.0)
    levels["solar"] = np.log(raw["solar"] + 1.0)
    levels["load"] = np.log(raw["load"] + 1.0)
    levels["price"] = np.log(raw["price"] + shift)
    levels = levels[ORDER].replace([np.inf, -np.inf], np.nan).dropna()
    diffs = levels.diff().dropna()
    return levels, diffs, shift


def stationarity_table(levels: pd.DataFrame, diffs: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for name, series in levels.items():
        for transform, s in [("level", series), ("diff", diffs[name])]:
            s = s.dropna()
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                adf_stat, adf_p, *_ = adfuller(s, autolag="AIC")
                try:
                    kpss_stat, kpss_p, *_ = kpss(s, regression="c", nlags="auto")
                except Exception:
                    kpss_stat, kpss_p = np.nan, np.nan
            rows.append(
                {
                    "variable": name,
                    "transform": transform,
                    "adf_stat": adf_stat,
                    "adf_p": adf_p,
                    "kpss_stat": kpss_stat,
                    "kpss_p": kpss_p,
                    "interpretation": (
                        "stationary"
                        if adf_p < 0.05 and (pd.isna(kpss_p) or kpss_p > 0.05)
                        else "nonstationary_or_mixed"
                    ),
                }
            )
    result = pd.DataFrame(rows)
    result.to_csv(TABLE_DIR / "table_stationarity_var42.csv", index=False, encoding="utf-8-sig")
    return result


def johansen_table(levels: pd.DataFrame) -> tuple[pd.DataFrame, int]:
    # k_ar_diff=1 corresponds to a VAR(2) in levels for the trace test.
    joh = coint_johansen(levels, det_order=0, k_ar_diff=1)
    rows = []
    for i in range(len(joh.lr1)):
        rows.append(
            {
                "null_rank": f"r <= {i}",
                "trace_stat": joh.lr1[i],
                "trace_crit_90": joh.cvt[i, 0],
                "trace_crit_95": joh.cvt[i, 1],
                "trace_crit_99": joh.cvt[i, 2],
                "reject_trace_95": bool(joh.lr1[i] > joh.cvt[i, 1]),
                "maxeig_stat": joh.lr2[i],
                "maxeig_crit_90": joh.cvm[i, 0],
                "maxeig_crit_95": joh.cvm[i, 1],
                "maxeig_crit_99": joh.cvm[i, 2],
                "reject_maxeig_95": bool(joh.lr2[i] > joh.cvm[i, 1]),
            }
        )
    table = pd.DataFrame(rows)
    table.to_csv(TABLE_DIR / "table_johansen_var42.csv", index=False, encoding="utf-8-sig")

    rank_res = select_coint_rank(levels, det_order=0, k_ar_diff=1, method="trace", signif=0.05)
    rank = int(rank_res.rank)
    return table, rank


def fit_vecm(levels: pd.DataFrame, rank: int) -> tuple[pd.DataFrame | None, pd.DataFrame | None]:
    stale_files = [
        TABLE_DIR / "table_vecm_alpha_var42.csv",
        TABLE_DIR / "table_vecm_beta_var42.csv",
        TABLE_DIR / "vecm_summary_var42.txt",
    ]
    if rank <= 0 or rank >= len(levels.columns):
        for file in stale_files:
            if file.exists():
                file.unlink()
        note = (
            f"Selected Johansen rank is {rank}. A reduced-rank VECM is only "
            f"estimated when 0 < rank < {len(levels.columns)}. The short-run "
            "analysis therefore uses a stationary VAR on first differences.\n"
        )
        (TABLE_DIR / "vecm_not_estimated_var42.txt").write_text(note, encoding="utf-8")
        return None, None
    res = VECM(levels, k_ar_diff=1, coint_rank=rank, deterministic="co").fit()
    alpha = pd.DataFrame(res.alpha, index=levels.columns, columns=[f"ec{i + 1}" for i in range(rank)])
    beta = pd.DataFrame(res.beta, index=levels.columns, columns=[f"beta{i + 1}" for i in range(rank)])
    alpha.to_csv(TABLE_DIR / "table_vecm_alpha_var42.csv", encoding="utf-8-sig")
    beta.to_csv(TABLE_DIR / "table_vecm_beta_var42.csv", encoding="utf-8-sig")
    (TABLE_DIR / "vecm_summary_var42.txt").write_text(str(res.summary()), encoding="utf-8")
    return alpha, beta


def fit_var(diffs: pd.DataFrame) -> tuple[object, pd.DataFrame, int]:
    model = VAR(diffs)
    selected = model.select_order(maxlags=14)
    order_table = pd.DataFrame(
        {
            "lag": list(range(0, 15)),
            "aic": selected.ics["aic"],
            "bic": selected.ics["bic"],
            "hqic": selected.ics["hqic"],
            "fpe": selected.ics["fpe"],
        }
    )
    order_table.to_csv(TABLE_DIR / "table_var_lag_selection_var42.csv", index=False, encoding="utf-8-sig")
    lag = int(selected.selected_orders.get("aic") or selected.selected_orders.get("bic") or 1)
    lag = max(1, lag)
    res = model.fit(lag)
    (TABLE_DIR / "var_summary_var42.txt").write_text(str(res.summary()), encoding="utf-8")
    return res, order_table, lag


def diagnostics(var_res, lag: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    roots = pd.DataFrame(
        {
            "root": var_res.roots,
            "modulus": np.abs(var_res.roots),
            "inverse_modulus": 1 / np.abs(var_res.roots),
        }
    )
    roots["stable_condition_modulus_gt_1"] = roots["modulus"] > 1
    roots.to_csv(TABLE_DIR / "table_var_roots_var42.csv", index=False, encoding="utf-8-sig")

    resid = pd.DataFrame(var_res.resid, columns=var_res.names)
    rows = []
    lb_lag = min(12, max(4, len(resid) // 10))
    for col in resid.columns:
        lb = acorr_ljungbox(resid[col], lags=[lb_lag], return_df=True)
        rows.append({"variable": col, "ljung_box_lag": lb_lag, "lb_stat": lb["lb_stat"].iloc[0], "lb_p": lb["lb_pvalue"].iloc[0]})
    diag = pd.DataFrame(rows)
    diag.to_csv(TABLE_DIR / "table_var_residual_diagnostics_var42.csv", index=False, encoding="utf-8-sig")
    return roots, diag


def granger_matrix(diffs: pd.DataFrame, max_lag: int) -> pd.DataFrame:
    rows = []
    pmat = pd.DataFrame(np.nan, index=ORDER, columns=ORDER)
    fmat = pd.DataFrame(np.nan, index=ORDER, columns=ORDER)
    max_lag = max(1, min(max_lag, 14))
    for cause in ORDER:
        for effect in ORDER:
            if cause == effect:
                continue
            data = diffs[[effect, cause]].dropna()
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                test = grangercausalitytests(data, maxlag=max_lag, verbose=False)
            candidates = []
            for lag_i, payload in test.items():
                f_stat, p_value, df_denom, df_num = payload[0]["ssr_ftest"]
                candidates.append((p_value, f_stat, lag_i, df_num, df_denom))
            p_value, f_stat, best_lag, df_num, df_denom = sorted(candidates, key=lambda x: x[0])[0]
            pmat.loc[cause, effect] = p_value
            fmat.loc[cause, effect] = f_stat
            rows.append(
                {
                    "cause": cause,
                    "effect": effect,
                    "best_lag_by_min_p": best_lag,
                    "f_stat": f_stat,
                    "p_value": p_value,
                    "df_num": df_num,
                    "df_denom": df_denom,
                    "significant_5pct": p_value < 0.05,
                }
            )
    detail = pd.DataFrame(rows).sort_values(["effect", "p_value"])
    pmat.to_csv(TABLE_DIR / "table_granger_pvalues_var42.csv", encoding="utf-8-sig")
    fmat.to_csv(TABLE_DIR / "table_granger_fstats_var42.csv", encoding="utf-8-sig")
    detail.to_csv(TABLE_DIR / "table_granger_detail_var42.csv", index=False, encoding="utf-8-sig")
    return pmat


def plot_granger_heatmap(pmat: pd.DataFrame) -> None:
    plt.figure(figsize=(7, 5.5))
    mask = pmat.isna()
    sns.heatmap(
        pmat.astype(float),
        annot=True,
        fmt=".3f",
        cmap="viridis_r",
        vmin=0,
        vmax=0.2,
        mask=mask,
        cbar_kws={"label": "p-value"},
    )
    plt.title("Granger Causality P-values\n(row causes column)")
    plt.xlabel("Effect")
    plt.ylabel("Cause")
    plt.tight_layout()
    plt.savefig(FIG_DIR / "fig_granger_heatmap_var42.png", dpi=220)
    plt.close()


def irf_and_fevd(var_res, periods: int = 20) -> tuple[pd.DataFrame, pd.DataFrame]:
    irf = var_res.irf(periods)
    fig = irf.plot(orth=True, signif=0.05)
    fig.set_size_inches(13, 10)
    fig.suptitle("Orthogonal Impulse Response Functions", y=1.01)
    plt.tight_layout()
    plt.savefig(FIG_DIR / "fig_irf_var42.png", dpi=220, bbox_inches="tight")
    plt.close(fig)

    responses = []
    price_idx = ORDER.index("price")
    for impulse in ORDER:
        imp_idx = ORDER.index(impulse)
        for h in range(periods + 1):
            responses.append(
                {
                    "horizon_days": h,
                    "impulse": impulse,
                    "response": "price",
                    "orth_irf": irf.orth_irfs[h, price_idx, imp_idx],
                }
            )
    price_irf = pd.DataFrame(responses)
    price_irf.to_csv(TABLE_DIR / "table_irf_price_responses_var42.csv", index=False, encoding="utf-8-sig")

    plt.figure(figsize=(8, 5))
    for impulse in ORDER:
        subset = price_irf[price_irf["impulse"] == impulse]
        plt.plot(subset["horizon_days"], subset["orth_irf"], marker="o", linewidth=1.4, label=impulse)
    plt.axhline(0, color="black", linewidth=0.8)
    plt.title("Price Responses to One-standard-deviation Shocks")
    plt.xlabel("Horizon (days)")
    plt.ylabel("Response in transformed price difference")
    plt.legend()
    plt.tight_layout()
    plt.savefig(FIG_DIR / "fig_price_irf_var42.png", dpi=220)
    plt.close()

    fevd = var_res.fevd(periods)
    fig = fevd.plot(figsize=(12, 8))
    plt.tight_layout()
    plt.savefig(FIG_DIR / "fig_fevd_var42.png", dpi=220, bbox_inches="tight")
    plt.close(fig)

    decomp = fevd.decomp
    fevd_rows = []
    for variable_idx, variable in enumerate(ORDER):
        for h in range(periods):
            for shock_idx, shock in enumerate(ORDER):
                fevd_rows.append(
                    {
                        "variable": variable,
                        "horizon_days": h + 1,
                        "shock": shock,
                        "share": decomp[variable_idx, h, shock_idx],
                    }
                )
    fevd_table = pd.DataFrame(fevd_rows)
    fevd_table.to_csv(TABLE_DIR / "table_fevd_all_var42.csv", index=False, encoding="utf-8-sig")
    price_fevd = fevd_table[fevd_table["variable"] == "price"].pivot(index="horizon_days", columns="shock", values="share")
    price_fevd.to_csv(TABLE_DIR / "table_fevd_price_var42.csv", encoding="utf-8-sig")
    return price_irf, price_fevd


def fmt_p(x: float) -> str:
    if pd.isna(x):
        return ""
    if x < 0.001:
        return "<0.001"
    return f"{x:.3f}"


def build_result_markdown(
    raw: pd.DataFrame,
    levels: pd.DataFrame,
    shift: float,
    stationarity: pd.DataFrame,
    johansen: pd.DataFrame,
    rank: int,
    order_table: pd.DataFrame,
    lag: int,
    roots: pd.DataFrame,
    diag: pd.DataFrame,
    pmat: pd.DataFrame,
    price_irf: pd.DataFrame,
    price_fevd: pd.DataFrame,
) -> str:
    sample_start = raw.index.min().date()
    sample_end = raw.index.max().date()
    n_raw = len(raw)
    n_diff = len(levels.diff().dropna())
    stable = bool((roots["modulus"] > 1).all())
    inv_max = roots["inverse_modulus"].max()

    price_causes = pmat["price"].dropna().sort_values()
    notable = "、".join([f"{c}→price p={fmt_p(p)}" for c, p in price_causes.items()])
    price_to_supply = "；".join([f"price→{c} p={fmt_p(pmat.loc['price', c])}" for c in ["wind", "solar", "load"]])
    if 0 < rank < len(ORDER):
        vecm_sentence = (
            f"Johansen trace 检验的结果见 `tables/table_johansen_var42.csv`。在 5% 显著性水平下选择的协整秩为 r={rank}。"
            "这说明变量之间存在长期均衡信息，已额外估计 VECM 并输出 `table_vecm_alpha_var42.csv` 与 "
            "`table_vecm_beta_var42.csv`；短期冲击传导和因果检验仍使用差分 VAR，以满足平稳性要求。"
        )
    elif rank >= len(ORDER):
        vecm_sentence = (
            f"Johansen trace 检验的结果见 `tables/table_johansen_var42.csv`。在 5% 显著性水平下，检验连续拒绝到 r≤3，"
            f"选择秩为 r={rank}（满秩）。这不是常规的低秩协整情形，因此没有估计 reduced-rank VECM；"
            "本节将一阶差分后的平稳序列用于 VAR、Granger、IRF 与 FEVD。"
        )
    else:
        vecm_sentence = (
            "Johansen trace 检验的结果见 `tables/table_johansen_var42.csv`。在 5% 显著性水平下不能拒绝 r=0，"
            "未发现显著协整关系，因此不估计 VECM；后续使用一阶差分 VAR。"
        )

    h3 = price_irf[price_irf["horizon_days"].between(1, 3)]
    irf_summary = (
        h3.groupby("impulse")["orth_irf"]
        .mean()
        .reindex(ORDER)
        .to_dict()
    )
    fevd20 = price_fevd.iloc[-1].reindex(ORDER)
    supply_share = float(fevd20[["wind", "solar", "load"]].sum())
    own_share = float(fevd20["price"])

    lines = [
        "# 4.2 VAR / VECM 与 Granger 因果分析结果说明",
        "",
        "## 数据与变换",
        "",
        f"本节使用清洗后的日频面板数据，样本期为 {sample_start} 至 {sample_end}，共 {n_raw} 个日观测；一阶差分后用于 VAR/Granger 的有效样本为 {n_diff} 个。变量排序采用 wind → solar → load → price。由于日均日前电价存在 {int((raw['price'] <= 0).sum())} 个非正观测，本文对价格使用 `log(price + %.6g)` 的平移对数变换；负荷、风电、光伏使用 `log(x + 1)`。" % shift,
        "",
        "## 单位根与协整",
        "",
        "ADF/KPSS 结果见 `tables/table_stationarity_var42.csv`。水平变量整体表现出非平稳或混合特征，而一阶差分后 ADF 均显著拒绝单位根，因此后续 Granger、IRF 与 FEVD 基于平稳的一阶差分 VAR 进行。",
        "",
        vecm_sentence,
        "",
        "## VAR 选阶与稳定性",
        "",
        f"AIC 在 0–14 日候选滞后中选择 p={lag}。模型稳定性检验显示所有根的模均大于 1，稳定性结论为 `{stable}`，最大逆根模为 {inv_max:.3f}。残差 Ljung-Box 检验见 `table_var_residual_diagnostics_var42.csv`。",
        "",
        "## Granger 因果",
        "",
        f"Granger p 值矩阵见 `tables/table_granger_pvalues_var42.csv`，热力图见 `figures/fig_granger_heatmap_var42.png`。针对电价方程，{notable}。价格到供给和负荷变量的反向检验为：{price_to_supply}。",
        "",
        "从经济含义看，风电、光伏和负荷对日前电价均具有明显的领先信息，这与 merit-order 机制和需求侧压力一致。部分反向 Granger 关系也达到统计显著，但它们应理解为时间序列预测信息而非物理因果：天气驱动的风光出力不可能由市场价格直接决定。",
        "",
        "## IRF 与 FEVD",
        "",
        "脉冲响应图见 `figures/fig_irf_var42.png` 和 `figures/fig_price_irf_var42.png`。价格对 1–3 日冲击的平均正交响应如下："
    ]
    for impulse, value in irf_summary.items():
        lines.append(f"- {impulse} 冲击：{value:.4f}")
    lines.extend(
        [
            "",
            f"20 日预测误差方差分解显示，price 自身冲击解释约 {own_share * 100:.1f}%；wind、solar、load 合计解释约 {supply_share * 100:.1f}%，其中 wind={fevd20['wind'] * 100:.1f}%，solar={fevd20['solar'] * 100:.1f}%，load={fevd20['load'] * 100:.1f}%。完整表格见 `tables/table_fevd_price_var42.csv`。",
            "",
            "## 文件清单",
            "",
            "- `code/run_var42_analysis.py`：完整可复跑分析脚本。",
            "- `tables/`：输入数据、单位根、Johansen、VECM、VAR 选阶、稳定性、残差诊断、Granger、IRF 和 FEVD 表。",
            "- `figures/`：Granger 热力图、IRF、价格响应曲线和 FEVD 图。",
            "- `论文写作模板_var_已修改.md`：已将 4.2 节替换为基于本次实证结果的版本。",
        ]
    )
    return "\n".join(lines) + "\n"


def build_section_42(
    raw: pd.DataFrame,
    shift: float,
    rank: int,
    lag: int,
    roots: pd.DataFrame,
    pmat: pd.DataFrame,
    price_irf: pd.DataFrame,
    price_fevd: pd.DataFrame,
) -> str:
    sample_start = raw.index.min().date()
    sample_end = raw.index.max().date()
    n_raw = len(raw)
    n_diff = n_raw - 1
    stable = bool((roots["modulus"] > 1).all())
    inv_max = roots["inverse_modulus"].max()
    h3 = price_irf[price_irf["horizon_days"].between(1, 3)].groupby("impulse")["orth_irf"].mean().reindex(ORDER)
    fevd20 = price_fevd.iloc[-1].reindex(ORDER)
    supply_share = fevd20[["wind", "solar", "load"]].sum()

    p_wind_price = pmat.loc["wind", "price"]
    p_solar_price = pmat.loc["solar", "price"]
    p_load_price = pmat.loc["load", "price"]
    p_price_wind = pmat.loc["price", "wind"]
    p_price_solar = pmat.loc["price", "solar"]
    p_price_load = pmat.loc["price", "load"]

    if 0 < rank < len(ORDER):
        vecm_paragraph = (
            f"Johansen trace 检验在 5% 水平下选择的协整秩为 $r={rank}$。因此，四变量系统存在长期均衡信息，"
            "本文同时估计 VECM 以保存长期调整项，协整向量与调整速度分别见 "
            "`VAR4.2/tables/table_vecm_beta_var42.csv` 和 `VAR4.2/tables/table_vecm_alpha_var42.csv`。"
            "在实证解释中，长期关系由 VECM 承担；短期因果和冲击响应使用平稳的一阶差分 VAR。"
        )
    elif rank >= len(ORDER):
        vecm_paragraph = (
            f"Johansen trace 检验在 5% 水平下连续拒绝 $r\\leq0$ 至 $r\\leq3$，选择秩为 $r={rank}$（满秩）。"
            "这并非通常意义下的低秩协整结构，因此本文不估计 reduced-rank VECM，而将其解释为系统不需要额外误差修正项；"
            "后续短期因果、IRF 与 FEVD 均基于平稳的一阶差分 VAR。"
        )
    else:
        vecm_paragraph = (
            "Johansen trace 检验在 5% 水平下不能拒绝 $r=0$，未发现显著协整关系。因此本文不估计 VECM，"
            "后续短期因果、IRF 与 FEVD 均基于平稳的一阶差分 VAR。"
        )

    return f"""### 4.2 VAR / VECM 与 Granger 因果

**本节目的**：在日频系统中检验负荷、风电、光伏与 DE-AT-LU 日前电价之间的动态领先关系，并用 IRF 与 FEVD 解释冲击如何传导到电价。

#### 4.2.1 应用对象与数据变换

本文使用清洗后的 `de_panel_daily.csv`，样本期为 {sample_start} 至 {sample_end}，共 {n_raw} 个日观测。变量向量按 Cholesky 识别顺序写为：

$$
\\mathbf{{y}}_t=(\\text{{wind}}_t,\\text{{solar}}_t,\\text{{load}}_t,\\text{{price}}_t)^\\top .
$$

对应代码列为 `DE_wind_generation_actual`、`DE_solar_generation_actual`、`DE_load_actual_entsoe_transparency` 与 `DE_price_day_ahead`。风电、光伏、负荷使用 $\\log(x+1)$ 变换；由于日均电价包含 {int((raw['price'] <= 0).sum())} 个非正观测，电价使用单调平移对数 $\\log(price+{shift:.4f})$。ADF/KPSS 检验显示水平变量存在非平稳或混合特征，而一阶差分后序列平稳，因此 Granger 因果、IRF 与 FEVD 均基于 $\\Delta\\mathbf{{y}}_t$ 估计。

#### 4.2.2 协整检验与 VECM

{vecm_paragraph}

#### 4.2.3 VAR 选阶与稳定性

在最大 14 日滞后范围内，AIC 选择 VAR($p={lag}$)。模型稳定性检验显示所有特征根的模均大于 1，最大逆根模为 {inv_max:.3f}，稳定性判断为 `{stable}`。这意味着基于该 VAR 的脉冲响应会随预测期延长逐步收敛，可以用于解释短期冲击传播。

#### 4.2.4 Granger 因果检验

Granger 因果矩阵见 `VAR4.2/tables/table_granger_pvalues_var42.csv`。针对日前电价方程，风电、光伏和负荷均提供显著领先信息：wind → price 的 p 值为 {fmt_p(p_wind_price)}，solar → price 的 p 值为 {fmt_p(p_solar_price)}，load → price 的 p 值为 {fmt_p(p_load_price)}。反向检验中，price → wind 的 p 值为 {fmt_p(p_price_wind)}，price → solar 的 p 值为 {fmt_p(p_price_solar)}，price → load 的 p 值为 {fmt_p(p_price_load)}。这些反向显著性应理解为预测意义上的领先信息，而不是结构性物理因果；供给端风光出力仍主要由天气和装机条件决定。

这一结果支持 merit-order 机制和需求侧压力机制：风光出力改变低边际成本电源在日前市场中的供给位置，负荷变化影响边际机组调用概率，因此三者都能领先解释电价变化。需要注意，Granger 因果不是结构因果，它检验的是滞后项是否提高预测能力。

#### 4.2.5 脉冲响应与方差分解

正交 IRF 采用 wind → solar → load → price 的 Cholesky 排序，理由是天气驱动的可再生出力先于需求和市场出清价格。价格对 1–3 日冲击的平均响应为：wind {h3['wind']:.4f}，solar {h3['solar']:.4f}，load {h3['load']:.4f}，price 自身 {h3['price']:.4f}。图形结果见 `VAR4.2/figures/fig_irf_var42.png` 与 `VAR4.2/figures/fig_price_irf_var42.png`。

FEVD 显示，在 20 日预测期上，price 自身冲击解释约 {fevd20['price'] * 100:.1f}% 的预测误差方差；wind、solar 与 load 合计解释约 {supply_share * 100:.1f}%，其中 wind 为 {fevd20['wind'] * 100:.1f}%，solar 为 {fevd20['solar'] * 100:.1f}%，load 为 {fevd20['load'] * 100:.1f}%。这说明日前电价的短期波动既有较强自身惯性，也受到供需端信息的系统影响。
"""


def write_modified_template(section_42: str) -> Path | None:
    """新平铺结构下没有论文模板，跳过该步骤。"""
    return None


def main() -> None:
    ensure_dirs()
    raw = load_daily_panel()
    levels, diffs, shift = transform_data(raw)
    levels.to_csv(TABLE_DIR / "table_transformed_levels_var42.csv", encoding="utf-8-sig")
    diffs.to_csv(TABLE_DIR / "table_transformed_diffs_var42.csv", encoding="utf-8-sig")

    stationarity = stationarity_table(levels, diffs)
    johansen, rank = johansen_table(levels)
    fit_vecm(levels, rank)
    var_res, order_table, lag = fit_var(diffs)
    roots, diag = diagnostics(var_res, lag)
    pmat = granger_matrix(diffs, lag)
    plot_granger_heatmap(pmat)
    price_irf, price_fevd = irf_and_fevd(var_res, periods=20)

    md = build_result_markdown(
        raw,
        levels,
        shift,
        stationarity,
        johansen,
        rank,
        order_table,
        lag,
        roots,
        diag,
        pmat,
        price_irf,
        price_fevd,
    )
    (TABLE_DIR / "var_result_notes.md").write_text(md, encoding="utf-8")
    write_modified_template(build_section_42(raw, shift, rank, lag, roots, pmat, price_irf, price_fevd))

    print(f"Done. Outputs written to: {OUT}")


if __name__ == "__main__":
    main()
